#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# This file is part of Yaner.

# Yaner - GTK+ interface for aria2 download mananger
# Copyright (C) 2010  Iven Day <ivenvd#gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
    This is the entry to the main application of Yaner, and should be
placed under a directory in $PATH.
    We just do some requirement checking here, and then load the main
window of the application.
"""
import pygtk
pygtk.require('2.0')
import gtk

if gtk.pygtk_version < (2, 12, 0):
    raise SystemExit(' * Error: PyGtk 2.12.0 or later required')

try:
    from twisted.internet import gtk2reactor
except ImportError:
    raise SystemExit(' * Error: the "twisted" module is missing. \
            Check if it is installed properly.')
else:
    gtk2reactor.install()
    from twisted.internet import reactor

#try:
    from Yaner.Application import YanerApp
#except ImportError:
#    raise SystemExit(' * Error: the "yaner" module is missing. \
#            Check if it is installed properly.')

YanerApp()
reactor.run()
