#!/usr/bin/env python2
# vim:fileencoding=UTF-8

# This file is part of Yaner.

# Yaner - GTK+ interface for aria2 download mananger
# Copyright (C) 2010-2011  Iven <ivenvd#gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
    This is the entry to the main application of yaner, and should be
placed under a directory in $PATH.
    We just do some requirement checking here, and then load the main
window of the application.
"""

try:
    import gi
except ImportError:
    raise SystemExit(' * Error: pygobject required')

try:
    gi.require_version('Gtk', '3.0')
except ValueError:
    raise SystemExit(' * Error: Gtk3 required')

try:
    from gi.repository import Notify
except ImportError:
    raise SystemExit(' * Error: libnotify required')
else:
    Notify.init('yaner')

# Translation setup
import gettext
gettext.install('yaner')

from yaner.Application import Application
main_app = Application()
main_app.run()

